apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pd-to-slack
  namespace: jobs
spec:
  schedule: "* * * * 1,2,3,4,5"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pd-to-slack
        spec: 
          containers:
          - name: pd-to-slack
            image: arranf/pd-to-slack:0.1.6
            env:
            - name: SCHEDULE_IDS
              value: PUNRLYL,PA60AJX
            envFrom:
            - secretRef:
                name: pd-to-slack-secrets
                optional: false
          restartPolicy: OnFailure
