apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: grafana
  chart:
    version: 5.0.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
  values:
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      existingClaim: grafana