apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: grafana
  chart:
    version: 5.0.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
  values:
    image:
      tag: 6.7.1-ubuntu
    resources:
        limits:
          cpu: 1000m
          memory: 10242Mi
        requests:
          cpu: 50m
          memory: 512Mi
    service:
      type: LoadBalancer
    livenessProbe: 
    envFromSecret: grafana-secret      
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: manual