---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/metrics"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi