apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  namespace: storage
provisioner: kubernetes.io/NFS
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate