helmOperator:
  create: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
git:
  url: "git@github.com:arranf/flux.git"
  branch: master
  path: namespaces
image:
  repository: raspbernetes/flux
  tag: 1.18.0
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
