helmOperator:
  create: false
git:
  url: "git@github.com:arranf/flux.git"
  branch: master
  path: namespaces
image:
  repository: raspbernetes/flux
  tag: 1.18.0
registry:
  rps: 100
  burst: 30
  automationInterval: 1m
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
