---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/influxdb"
---
