apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: influxdb
  chart:
    version: 4.4.3
    repository: https://influxdata.github.io/helm-charts
    name: influxdb
  values:
    persistence:
        existingClaim: metrics-volume