apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: influxdb
  chart:
    repository: https://helm.influxdata.com/
    name: influxdb
    persistence:
        existingClaim: metrics-volume